### ISSUE TITLE
Templates for prompts in "Awesome ChatGPT Prompts"

### ISSUE THREAD

**Issue by zsh-eng** [bramses/chatgpt-md-templates#1]
I recently came across the repository and I found it to be extremely helpful.

I was wondering if there are any plans to include prompts from [Awesome ChatGPT Prompts](https://github.com/f/awesome-chatgpt-prompts). I think it would be a great addition! 

Are you accepting any pull requests for new templates?

**Comment by bramses** [comment]
Hi @zsh-eng 

Yeah please feel free to PR
